WIDTH = 1200
HEIGHT = 650
CARD_SUITS = ["HEARTS", "DIAMONDS", "CLUBS", "SPADES"]
CARD_DIMENSION = (100, 140)
CARD_SPACING = 20
TOP_ROW_Y = 20
BASE_ROW_XY = (200, 180)  # bottom row cards start point

CARD_HOLDER_VERTICAL_OFFSET = 30

MOUSE_HOLDER_OFFSET = (0, CARD_HOLDER_VERTICAL_OFFSET)
TOP_LEFT_HOLDER_OFFSET = (30, 0)
TOP_RIGHT_HOLDER_OFFSET = (0, 0)
BASE_HOLDER_OFFSET = (0, CARD_HOLDER_VERTICAL_OFFSET)

RESTART_BUTTON_SIZE = (100, 100)
RESTART_BUTTON_POSITION = (10, 550)
